name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
    
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: npm run build:win
    
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: goodrest-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          goodrest-ubuntu-latest/**/*
          goodrest-windows-latest/**/*
          goodrest-macos-latest/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}